---
- name: Configure Linux Mint workstations
  hosts: all
  become: true

  roles:
    - base
    - software
    - users

    - role: postgresql
      tags:
        - postgresql

    - role: pokladna
      tags:
        - pokladna

    - remote_access
    - cinnamon
